### ISSUE TITLE
Click event on markers not firing

### ISSUE THREAD

**Issue by BrianCohen** [zhenyanghua/MeasureTool-GoogleMaps-V3#12] opened 2017-08-03 10:44 UTC
When the MeasureTool is instantiated, click events on markers added through angular-google-maps stop working. It works some times though, but then reload the same page and it's not working again. Shapes are not affected, also are not added through angular-google-maps. I don't know if it's an issue with angular-google-maps or MeasureTool.

Maybe there's a way to disable functionalities and keep the basic needed ones to see if the problem is avoided this way? I just need to be able to start the tool through my own menu (no context menu needed) and click to get the distances between the successive points then stop the tool altogether with my own menu again, so no need to drag or click point to remove.

Thank you.

**Comment by zhenyanghua** [comment] 2017-10-16 12:16
This library doesn't have any code performing marker event registration and removal. please post the question to angular-google-maps page and see if it can be solved.

**Comment by Intrepiware** [comment] 2018-03-19 18:32
@zhenyanghua I am also experiencing this issue. Here is a working example: https://codepen.io/anon/pen/ZxLbLK?editors=0010. I am able to click on Marker 1, but not Marker 2. However, if I activate and deactivate MeasureTool (i.e.: right-click, "Measure Distance", right-click, "Clear Measurement"), the Marker 2 click event fires.

My apologies if I should have opened a separate bug for this. Let me know, and I'll open one if needed.

**Comment by zhenyanghua** [comment] 2018-03-19 19:21
I tried on my local dev machine and another online editor - [jsbin](https://jsbin.com/doxutigixi/1/edit?html,output), cannot reproduce the error, but can reproduce the error inconsistently on the codepen. I consider that might be something with SVG on codepen. Have you tried it in your local dev server?

**Comment by Intrepiware** [comment] 2018-03-19 19:39
@zhenyanghua Yes, the bug was discovered on my local dev server. It works fairly reliably for me when the window is maximized to full screen width. I was able to reproduce the bug on jsbin as well: https://jsbin.com/pogaxikawi/2/edit?output

In case it's relevant, I'm on a Windows machine, and the issue appears in both Firefox and Chrome.

**Comment by zhenyanghua** [comment] 2018-03-19 19:56
Try again with this [example](https://jsbin.com/wazujogopo/edit?html,output), does it work?

**Comment by Intrepiware** [comment] 2018-03-19 20:03
Yes, that one works on my end.

**Comment by zhenyanghua** [comment] 2018-03-19 20:25
I am not sure why the one you provided doesn't work. But try to use the latest release. If that one works, make sure the /example project works in your dev env.

**Comment by Intrepiware** [comment] 2018-03-20 20:11
Here is a fork of your example; I only changed the marker coordinates, map center, and zoom level: https://jsbin.com/gaqowuleji/1/edit?output

I still cannot click on Marker 2. I've tried on multiple computers and in multiple browsers.

Is there a way to debug this to see what object is on top? Possibly through the web development tools, or the like?

**Comment by zhenyanghua** [comment] 2018-03-20 23:29
This was caused by a line of code that takes over the svg overlay. A newer release v0.1.2 resolved this problem. Please close this issue when you locally test this.

**Comment by zhenyanghua** [comment] 2018-03-20 23:41
This snapshot uses v0.1.2 as the lib source. https://jsbin.com/detuqegaqo/1/edit?output

**Comment by zhenyanghua** [comment] 2018-03-22 12:52
Fixed in v0.1.4

**Closed by zhenyanghua** 2018-03-22 12:52 UTC
Labels: bug
