### ISSUE TITLE
Measure Tool does not work after Clear Measurement

### ISSUE THREAD

**Issue by marywholey** [zhenyanghua/MeasureTool-GoogleMaps-V3#29] opened 2018-02-19 23:50 UTC
I can duplicate this at http://zhenyanghua.github.io/google-maps/measure-tool/

- Create a distance measurement
- Right click and clear measurement 
- Try to measure distance again - the tool does not respond.

Any way to work around?

**Comment by zhenyanghua** [comment] 2018-02-19 23:54
This is caused by an internal `OverlayView` class change. I will push a fix for this change. #28 is caused by the same change.

**Comment by zhenyanghua** [comment] 2018-02-20 00:10
Fixed in [#732c1da](https://github.com/zhenyanghua/MeasureTool-GoogleMaps-V3/commit/732c1da4b4d4e2ba6ba9367d00bd66fcc1916245), updated npm release to v0.0.10

**Closed by zhenyanghua** 2018-02-20 00:10 UTC
Labels: bug
